name: Deploy nodejs application to hostinger

on:
  push:
    braches:
      -main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/Checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST}}
          username: root
          key: ${{ secrets.SSH_KEY }}
          script:
            cd /root/nodejs-application-deploy-github-action
            git pull
            docker compose up -d --build
