name: Deploy nodejs application to hostinger

on:
  push:
    braches:
      -main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/Checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST}}
          userrname: root
          key: ${{ secrets.SSH_KEY }}
          script:
            cd /root/nodejs-application-deploy-github-action
            git pull
            docker compose up -d --build
